version: "3"
services:
  app:
    build: Dockerfile.dev
    restart: always
    env_file: .env
    network_mode: host
    image: fastapi-admin
    command: uvicorn examples.main:app_ --port 8000 --host 0.0.0.0
