"""empty message

Revision ID: 00f8ea3d4aaa
Revises: 3190d0ad8a3f
Create Date: 2024-05-13 18:05:37.197251

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '00f8ea3d4aaa'
down_revision = '3190d0ad8a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'level')
    # ### end Alembic commands ###
