"""empty message

Revision ID: 061b50584f94
Revises: ce56b800ed02
Create Date: 2024-05-13 18:24:17.068687

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '061b50584f94'
down_revision = 'ce56b800ed02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
