"""empty message

Revision ID: 18971997bc22
Revises: 7f79f66d2681
Create Date: 2024-05-13 18:47:53.861816

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '18971997bc22'
down_revision = '7f79f66d2681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'badges')
    op.drop_column('profile', 'friends')
    op.drop_column('profile', 'completed_rooms')
    op.drop_column('profile', 'created_rooms')
    op.drop_column('profile', 'active_room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('active_room', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('profile', sa.Column('created_rooms', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profile', sa.Column('completed_rooms', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profile', sa.Column('friends', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profile', sa.Column('badges', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
