"""empty message

Revision ID: 3190d0ad8a3f
Revises: e5d43deeb583
Create Date: 2024-05-13 18:04:42.145865

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3190d0ad8a3f'
down_revision = 'e5d43deeb583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
