"""Add file field to Room

Revision ID: 411993cc2aa3
Revises: 76b59a0af0cd
Create Date: 2024-04-29 16:21:39.370376

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '411993cc2aa3'
down_revision = '76b59a0af0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mazes', sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mazes', 'file_name')
    # ### end Alembic commands ###
