"""empty message

Revision ID: e9d92231cb5a
Revises: d1b7a8a9d061
Create Date: 2024-05-13 19:45:40.320211

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e9d92231cb5a'
down_revision = 'd1b7a8a9d061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
