"""empty message

Revision ID: 191ed36032ac
Revises: e71fd4aae712
Create Date: 2024-02-16 17:37:57.241614

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '191ed36032ac'
down_revision = 'e71fd4aae712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
